name: CI - With Fastlane

env:
    GITHUB_TOKEN: ${{secrets.PAT_GITHUB}}
    COCOA_POD_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN}}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}
    GITHUB_BUILD_BRANCH: ${{ github.ref_name }}

permissions:
  contents: read
  actions: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - "**.podspec"
  schedule:
    - cron: '0 1 * * 1' # This cron expression means "At 01:00 on Monday"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'development' }}

jobs:
  build-iOS: 
     name: "Buidling iOS source code"
     uses: ./.github/workflows/readConfigFileAndPassToAction.yml # Create new repo and paste this in work flow and class like this awasthi027/repoName/.github/workflows/readConfigFileAndPassToAction.yml@main
     with: 
       config_path: './.github/ci-configuration/ci.json'
     secrets: inherit
  

