name: CI-Publish- With Fastlane

env:
    GITHUB_TOKEN: ${{secrets.PAT_GITHUB}}
    COCOA_POD_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN}}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}
    GITHUB_BUILD_BRANCH: ${{ github.ref_name }}

permissions:
  contents: read
  actions: read
  checks: write

on:
  workflow_dispatch:

jobs:
  build-iOS: 
     name: "Publish Things"
     uses: ./.github/workflows/readConfigFileAndPassToAction_publish.yml
     with: 
       config_path: './.github/cd-configuration/cd_publish.json'
     secrets: inherit
  