name: Fastlane With Tow Jobs

env:
    GITHUB_TOKEN: ${{secrets.PAT_GITHUB}}
    COCOA_POD_TOKEN: ${{secrets.COCOAPODS_TRUNK_TOKEN}}
    GITHUB_BUILD_NUMBER: ${{ github.run_number }}
    GITHUB_BUILD_BRANCH: ${{ github.ref_name }}

permissions:
  contents: read
  actions: read
  checks: write

on:
  workflow_dispatch:
    
jobs:
  build-iOS: 
     name: "Buidling iOS source code"
     uses: ./.github/workflows/executeTwoJobs.yml
     with: 
       config_path: './.github/ci-configuration/ci-two-jobs.json'
     secrets: inherit
  

